// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using Pgvector;
using RagChatbotSystem.DataAccess.Data;

#nullable disable

namespace RagChatbotSystem.DataAccess.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260716161342_AddEmbeddingScores")]
    partial class AddEmbeddingScores
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.HasPostgresExtension(modelBuilder, "vector");
            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("RagChatbotSystem.DataAccess.Models.ChatMessage", b =>
                {
                    b.Property<Guid>("MessageId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<Guid>("SessionId")
                        .HasColumnType("uuid");

                    b.HasKey("MessageId");

                    b.HasIndex("SessionId");

                    b.ToTable("ChatMessages");
                });

            modelBuilder.Entity("RagChatbotSystem.DataAccess.Models.ChatSession", b =>
                {
                    b.Property<Guid>("SessionId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("DatasetId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("StartedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("SessionId");

                    b.HasIndex("DatasetId");

                    b.HasIndex("UserId");

                    b.ToTable("ChatSessions");
                });

            modelBuilder.Entity("RagChatbotSystem.DataAccess.Models.Chunk", b =>
                {
                    b.Property<Guid>("ChunkId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("ChunkIndex")
                        .HasColumnType("integer");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("DatasetId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("DocumentId")
                        .HasColumnType("uuid");

                    b.Property<string>("MetadataJson")
                        .HasColumnType("jsonb");

                    b.Property<int>("PageNumber")
                        .HasColumnType("integer");

                    b.Property<string>("SectionTitle")
                        .HasColumnType("text");

                    b.HasKey("ChunkId");

                    b.HasIndex("DatasetId");

                    b.HasIndex("DocumentId");

                    b.ToTable("Chunks");
                });

            modelBuilder.Entity("RagChatbotSystem.DataAccess.Models.Citation", b =>
                {
                    b.Property<Guid>("CitationId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("ChunkId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("DocumentId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("MessageId")
                        .HasColumnType("uuid");

                    b.Property<int>("PageNumber")
                        .HasColumnType("integer");

                    b.Property<string>("QuoteText")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("SourceLabel")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.HasKey("CitationId");

                    b.HasIndex("ChunkId");

                    b.HasIndex("DocumentId");

                    b.HasIndex("MessageId");

                    b.ToTable("Citations");
                });

            modelBuilder.Entity("RagChatbotSystem.DataAccess.Models.CreditBlockedAttempt", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid?>("ChatSessionId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int?>("DailyTokenLimit")
                        .HasColumnType("integer");

                    b.Property<Guid?>("DatasetId")
                        .HasColumnType("uuid");

                    b.Property<int>("FreeCreditsAtTime")
                        .HasColumnType("integer");

                    b.Property<string>("MessagePreview")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<string>("Note")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<int>("PaidCreditsAtTime")
                        .HasColumnType("integer");

                    b.Property<string>("Reason")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)");

                    b.Property<int?>("UsedTokensToday")
                        .HasColumnType("integer");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("ChatSessionId");

                    b.HasIndex("DatasetId");

                    b.HasIndex("Reason", "CreatedAt");

                    b.HasIndex("UserId", "CreatedAt");

                    b.ToTable("CreditBlockedAttempts");
                });

            modelBuilder.Entity("RagChatbotSystem.DataAccess.Models.CreditLedger", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("BalanceAfterFree")
                        .HasColumnType("integer");

                    b.Property<int>("BalanceAfterPaid")
                        .HasColumnType("integer");

                    b.Property<int>("BalanceBeforeFree")
                        .HasColumnType("integer");

                    b.Property<int>("BalanceBeforePaid")
                        .HasColumnType("integer");

                    b.Property<int>("CalculatedCredits")
                        .HasColumnType("integer");

                    b.Property<int>("ChargedCredits")
                        .HasColumnType("integer");

                    b.Property<Guid?>("ChatMessageId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("ChatSessionId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("CreatedByUserId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("DatasetId")
                        .HasColumnType("uuid");

                    b.Property<int>("FreeCreditsAdded")
                        .HasColumnType("integer");

                    b.Property<int>("FreeCreditsUsed")
                        .HasColumnType("integer");

                    b.Property<int>("InputTokens")
                        .HasColumnType("integer");

                    b.Property<string>("ModelName")
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)");

                    b.Property<string>("Note")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<int>("OutputTokenWeight")
                        .HasColumnType("integer");

                    b.Property<int>("OutputTokens")
                        .HasColumnType("integer");

                    b.Property<int>("PaidCreditsAdded")
                        .HasColumnType("integer");

                    b.Property<int>("PaidCreditsUsed")
                        .HasColumnType("integer");

                    b.Property<Guid?>("RelatedPackageId")
                        .HasColumnType("uuid");

                    b.Property<int>("TokenUnit")
                        .HasColumnType("integer");

                    b.Property<int>("TotalTokens")
                        .HasColumnType("integer");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.Property<bool>("WasActualTokenUsage")
                        .HasColumnType("boolean");

                    b.Property<bool>("WasInsufficientBalance")
                        .HasColumnType("boolean");

                    b.HasKey("Id");

                    b.HasIndex("ChatMessageId");

                    b.HasIndex("ChatSessionId");

                    b.HasIndex("CreatedByUserId");

                    b.HasIndex("RelatedPackageId");

                    b.HasIndex("DatasetId", "CreatedAt");

                    b.HasIndex("ModelName", "CreatedAt");

                    b.HasIndex("Type", "CreatedAt");

                    b.HasIndex("UserId", "CreatedAt");

                    b.ToTable("CreditLedgers", t =>
                        {
                            t.HasCheckConstraint("CK_CreditLedger_BalanceAfterFree_NonNegative", "\"BalanceAfterFree\" >= 0");

                            t.HasCheckConstraint("CK_CreditLedger_BalanceAfterPaid_NonNegative", "\"BalanceAfterPaid\" >= 0");

                            t.HasCheckConstraint("CK_CreditLedger_BalanceBeforeFree_NonNegative", "\"BalanceBeforeFree\" >= 0");

                            t.HasCheckConstraint("CK_CreditLedger_BalanceBeforePaid_NonNegative", "\"BalanceBeforePaid\" >= 0");

                            t.HasCheckConstraint("CK_CreditLedger_CalculatedCredits_NonNegative", "\"CalculatedCredits\" >= 0");

                            t.HasCheckConstraint("CK_CreditLedger_ChargedCredits_NonNegative", "\"ChargedCredits\" >= 0");

                            t.HasCheckConstraint("CK_CreditLedger_FreeCreditsAdded_NonNegative", "\"FreeCreditsAdded\" >= 0");

                            t.HasCheckConstraint("CK_CreditLedger_FreeCreditsUsed_NonNegative", "\"FreeCreditsUsed\" >= 0");

                            t.HasCheckConstraint("CK_CreditLedger_PaidCreditsAdded_NonNegative", "\"PaidCreditsAdded\" >= 0");

                            t.HasCheckConstraint("CK_CreditLedger_PaidCreditsUsed_NonNegative", "\"PaidCreditsUsed\" >= 0");

                            t.HasCheckConstraint("CK_CreditLedger_Tokens_NonNegative", "\"InputTokens\" >= 0 AND \"OutputTokens\" >= 0 AND \"TotalTokens\" >= 0");
                        });
                });

            modelBuilder.Entity("RagChatbotSystem.DataAccess.Models.CreditPackage", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("BaseCredits")
                        .HasColumnType("integer");

                    b.Property<int>("BonusCredits")
                        .HasColumnType("integer");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Currency")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<int>("DisplayOrder")
                        .HasColumnType("integer");

                    b.Property<int?>("ExpiresAfterDays")
                        .HasColumnType("integer");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)");

                    b.Property<decimal>("Price")
                        .HasColumnType("numeric(18,2)");

                    b.Property<int>("TotalCredits")
                        .HasColumnType("integer");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int?>("ValidDays")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.ToTable("CreditPackages", t =>
                        {
                            t.HasCheckConstraint("CK_CreditPackage_BaseCredits_Positive", "\"BaseCredits\" > 0");

                            t.HasCheckConstraint("CK_CreditPackage_BonusCredits_NonNegative", "\"BonusCredits\" >= 0");

                            t.HasCheckConstraint("CK_CreditPackage_Price_NonNegative", "\"Price\" >= 0");

                            t.HasCheckConstraint("CK_CreditPackage_TotalCredits_Positive", "\"TotalCredits\" > 0");
                        });

                    b.HasData(
                        new
                        {
                            Id = new Guid("10000000-0000-0000-0000-000000000001"),
                            BaseCredits = 300,
                            BonusCredits = 0,
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Currency = "VND",
                            Description = "Small top-up for regular study.",
                            DisplayOrder = 1,
                            IsActive = true,
                            Name = "Study Lite",
                            Price = 10000m,
                            TotalCredits = 300,
                            UpdatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = new Guid("10000000-0000-0000-0000-000000000002"),
                            BaseCredits = 700,
                            BonusCredits = 100,
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Currency = "VND",
                            Description = "Better value for active learners.",
                            DisplayOrder = 2,
                            IsActive = true,
                            Name = "Study Plus",
                            Price = 25000m,
                            TotalCredits = 800,
                            UpdatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = new Guid("10000000-0000-0000-0000-000000000003"),
                            BaseCredits = 1700,
                            BonusCredits = 300,
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Currency = "VND",
                            Description = "Recommended for quiz/PE/final preparation.",
                            DisplayOrder = 3,
                            IsActive = true,
                            Name = "Exam Boost",
                            Price = 59000m,
                            TotalCredits = 2000,
                            UpdatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = new Guid("10000000-0000-0000-0000-000000000004"),
                            BaseCredits = 4000,
                            BonusCredits = 1000,
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Currency = "VND",
                            Description = "Best value for intensive exam preparation.",
                            DisplayOrder = 4,
                            IsActive = true,
                            Name = "Final Sprint",
                            Price = 129000m,
                            TotalCredits = 5000,
                            UpdatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc)
                        });
                });

            modelBuilder.Entity("RagChatbotSystem.DataAccess.Models.CreditPurchase", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<decimal>("Amount")
                        .HasColumnType("numeric(18,2)");

                    b.Property<int>("BaseCredits")
                        .HasColumnType("integer");

                    b.Property<int>("BonusCredits")
                        .HasColumnType("integer");

                    b.Property<string>("CheckoutUrl")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<DateTime?>("CompletedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("CreatedByUserId")
                        .HasColumnType("uuid");

                    b.Property<string>("Currency")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)");

                    b.Property<Guid?>("PackageId")
                        .HasColumnType("uuid");

                    b.Property<string>("PaymentProvider")
                        .HasMaxLength(80)
                        .HasColumnType("character varying(80)");

                    b.Property<long?>("ProviderOrderCode")
                        .HasColumnType("bigint");

                    b.Property<string>("ProviderReference")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)");

                    b.Property<int>("TotalCredits")
                        .HasColumnType("integer");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("CreatedByUserId");

                    b.HasIndex("PackageId");

                    b.HasIndex("ProviderOrderCode")
                        .IsUnique();

                    b.HasIndex("Status", "CreatedAt");

                    b.HasIndex("UserId", "CreatedAt");

                    b.ToTable("CreditPurchases", t =>
                        {
                            t.HasCheckConstraint("CK_CreditPurchase_Amount_NonNegative", "\"Amount\" >= 0");

                            t.HasCheckConstraint("CK_CreditPurchase_BaseCredits_NonNegative", "\"BaseCredits\" >= 0");

                            t.HasCheckConstraint("CK_CreditPurchase_BonusCredits_NonNegative", "\"BonusCredits\" >= 0");

                            t.HasCheckConstraint("CK_CreditPurchase_TotalCredits_NonNegative", "\"TotalCredits\" >= 0");
                        });
                });

            modelBuilder.Entity("RagChatbotSystem.DataAccess.Models.CreditWallet", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("FreeCredits")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0);

                    b.Property<DateTime>("LastFreeCreditResetDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("PaidCredits")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0);

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.Property<long>("Version")
                        .IsConcurrencyToken()
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("UserId")
                        .IsUnique();

                    b.ToTable("CreditWallets", t =>
                        {
                            t.HasCheckConstraint("CK_CreditWallet_FreeCredits_NonNegative", "\"FreeCredits\" >= 0");

                            t.HasCheckConstraint("CK_CreditWallet_PaidCredits_NonNegative", "\"PaidCredits\" >= 0");
                        });
                });

            modelBuilder.Entity("RagChatbotSystem.DataAccess.Models.Dataset", b =>
                {
                    b.Property<Guid>("DatasetId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("ArchivedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("ArchivedBy")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("CreatedBy")
                        .HasColumnType("uuid");

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<bool>("IsApproved")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false);

                    b.Property<bool>("IsArchived")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false);

                    b.Property<bool>("IsPublic")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("DatasetId");

                    b.HasIndex("CreatedBy");

                    b.HasIndex("IsArchived");

                    b.ToTable("Datasets");
                });

            modelBuilder.Entity("RagChatbotSystem.DataAccess.Models.DatasetPermission", b =>
                {
                    b.Property<Guid>("PermissionId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("DatasetId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("GrantedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("PermissionId");

                    b.HasIndex("UserId");

                    b.HasIndex("DatasetId", "UserId")
                        .IsUnique();

                    b.ToTable("DatasetPermissions");
                });

            modelBuilder.Entity("RagChatbotSystem.DataAccess.Models.Document", b =>
                {
                    b.Property<Guid>("DocumentId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("DatasetId")
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("DeletedBy")
                        .HasColumnType("uuid");

                    b.Property<string>("FileHash")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<string>("FileName")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<string>("FilePath")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<long>("FileSize")
                        .HasColumnType("bigint");

                    b.Property<string>("FileType")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<bool>("IsDeleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false);

                    b.Property<string>("ProcessError")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("UploadedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("UploadedBy")
                        .HasColumnType("uuid");

                    b.HasKey("DocumentId");

                    b.HasIndex("UploadedBy");

                    b.HasIndex("DatasetId", "FileHash");

                    b.ToTable("Documents");
                });

            modelBuilder.Entity("RagChatbotSystem.DataAccess.Models.ModelComparisonResult", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Answer")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("ErrorMessage")
                        .HasColumnType("text");

                    b.Property<double?>("Faithfulness")
                        .HasColumnType("double precision");

                    b.Property<int>("InputTokens")
                        .HasColumnType("integer");

                    b.Property<bool>("IsSuccess")
                        .HasColumnType("boolean");

                    b.Property<long>("LatencyMs")
                        .HasColumnType("bigint");

                    b.Property<Guid>("ModelComparisonRunId")
                        .HasColumnType("uuid");

                    b.Property<string>("ModelName")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)");

                    b.Property<int>("OutputTokens")
                        .HasColumnType("integer");

                    b.Property<string>("ProviderKey")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("QualityReasoning")
                        .HasColumnType("text");

                    b.Property<int?>("QualityScore")
                        .HasColumnType("integer");

                    b.Property<double?>("Relevance")
                        .HasColumnType("double precision");

                    b.Property<int>("TotalTokens")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("ModelComparisonRunId");

                    b.HasIndex("ProviderKey", "ModelComparisonRunId");

                    b.ToTable("ModelComparisonResults");
                });

            modelBuilder.Entity("RagChatbotSystem.DataAccess.Models.ModelComparisonRun", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("DatasetId")
                        .HasColumnType("uuid");

                    b.Property<string>("Question")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<long>("RetrievalLatencyMs")
                        .HasColumnType("bigint");

                    b.Property<int>("RetrievedChunkCount")
                        .HasColumnType("integer");

                    b.Property<Guid>("RunByUserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("DatasetId", "CreatedAt");

                    b.HasIndex("RunByUserId", "CreatedAt");

                    b.ToTable("ModelComparisonRuns");
                });

            modelBuilder.Entity("RagChatbotSystem.DataAccess.Models.SystemSetting", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("ChunkOverlap")
                        .HasColumnType("integer");

                    b.Property<int>("ChunkSize")
                        .HasColumnType("integer");

                    b.Property<int>("CreditOutputTokenWeight")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(4);

                    b.Property<int>("CreditTokenUnit")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(1000);

                    b.Property<int>("DailyFreeCredits")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(60);

                    b.Property<int>("DailyTokenLimit")
                        .HasColumnType("integer");

                    b.Property<bool>("EnableCreditSystem")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true);

                    b.Property<int>("ExamSeasonDailyFreeCredits")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(100);

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.ToTable("SystemSettings");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            ChunkOverlap = 100,
                            ChunkSize = 500,
                            CreditOutputTokenWeight = 4,
                            CreditTokenUnit = 1000,
                            DailyFreeCredits = 60,
                            DailyTokenLimit = 50000,
                            EnableCreditSystem = true,
                            ExamSeasonDailyFreeCredits = 100,
                            UpdatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc)
                        });
                });

            modelBuilder.Entity("RagChatbotSystem.DataAccess.Models.TeacherSubjectAssignment", b =>
                {
                    b.Property<Guid>("AssignmentId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("AssignedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("AssignedBy")
                        .HasColumnType("uuid");

                    b.Property<Guid>("DatasetId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("TeacherId")
                        .HasColumnType("uuid");

                    b.HasKey("AssignmentId");

                    b.HasIndex("AssignedBy");

                    b.HasIndex("DatasetId")
                        .IsUnique();

                    b.HasIndex("TeacherId", "DatasetId")
                        .IsUnique();

                    b.ToTable("TeacherSubjectAssignments");
                });

            modelBuilder.Entity("RagChatbotSystem.DataAccess.Models.User", b =>
                {
                    b.Property<Guid>("UserId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("CreatedByAdminId")
                        .HasColumnType("uuid");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<bool>("IsApproved")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true);

                    b.Property<DateTime?>("LastLoginAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("LastPasswordChangedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("MustChangePassword")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false);

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<DateTime?>("TemporaryPasswordExpiresAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.HasKey("UserId");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.HasIndex("Username")
                        .IsUnique();

                    b.ToTable("Users");
                });

            modelBuilder.Entity("RagChatbotSystem.DataAccess.Models.UserTokenUsage", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("DatasetId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("Date")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("QueryCount")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0);

                    b.Property<int>("TokenCount")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0);

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("DatasetId");

                    b.HasIndex("UserId", "DatasetId", "Date")
                        .IsUnique();

                    b.ToTable("UserTokenUsages");
                });

            modelBuilder.Entity("RagChatbotSystem.DataAccess.Models.VectorRecord", b =>
                {
                    b.Property<Guid>("VectorId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("ChunkId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("DatasetId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("DocumentId")
                        .HasColumnType("uuid");

                    b.Property<Vector>("Embedding")
                        .IsRequired()
                        .HasColumnType("vector(384)");

                    b.Property<string>("EmbeddingModel")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.HasKey("VectorId");

                    b.HasIndex("ChunkId")
                        .IsUnique();

                    b.HasIndex("DatasetId");

                    b.HasIndex("DocumentId");

                    b.ToTable("VectorRecords");
                });

            modelBuilder.Entity("RagChatbotSystem.DataAccess.Models.ChatMessage", b =>
                {
                    b.HasOne("RagChatbotSystem.DataAccess.Models.ChatSession", "ChatSession")
                        .WithMany("ChatMessages")
                        .HasForeignKey("SessionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ChatSession");
                });

            modelBuilder.Entity("RagChatbotSystem.DataAccess.Models.ChatSession", b =>
                {
                    b.HasOne("RagChatbotSystem.DataAccess.Models.Dataset", "Dataset")
                        .WithMany("ChatSessions")
                        .HasForeignKey("DatasetId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("RagChatbotSystem.DataAccess.Models.User", "User")
                        .WithMany("ChatSessions")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Dataset");

                    b.Navigation("User");
                });

            modelBuilder.Entity("RagChatbotSystem.DataAccess.Models.Chunk", b =>
                {
                    b.HasOne("RagChatbotSystem.DataAccess.Models.Dataset", "Dataset")
                        .WithMany("Chunks")
                        .HasForeignKey("DatasetId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("RagChatbotSystem.DataAccess.Models.Document", "Document")
                        .WithMany("Chunks")
                        .HasForeignKey("DocumentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Dataset");

                    b.Navigation("Document");
                });

            modelBuilder.Entity("RagChatbotSystem.DataAccess.Models.Citation", b =>
                {
                    b.HasOne("RagChatbotSystem.DataAccess.Models.Chunk", "Chunk")
                        .WithMany("Citations")
                        .HasForeignKey("ChunkId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("RagChatbotSystem.DataAccess.Models.Document", "Document")
                        .WithMany("Citations")
                        .HasForeignKey("DocumentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("RagChatbotSystem.DataAccess.Models.ChatMessage", "ChatMessage")
                        .WithMany("Citations")
                        .HasForeignKey("MessageId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ChatMessage");

                    b.Navigation("Chunk");

                    b.Navigation("Document");
                });

            modelBuilder.Entity("RagChatbotSystem.DataAccess.Models.CreditBlockedAttempt", b =>
                {
                    b.HasOne("RagChatbotSystem.DataAccess.Models.ChatSession", "ChatSession")
                        .WithMany()
                        .HasForeignKey("ChatSessionId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("RagChatbotSystem.DataAccess.Models.Dataset", "Dataset")
                        .WithMany()
                        .HasForeignKey("DatasetId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("RagChatbotSystem.DataAccess.Models.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("ChatSession");

                    b.Navigation("Dataset");

                    b.Navigation("User");
                });

            modelBuilder.Entity("RagChatbotSystem.DataAccess.Models.CreditLedger", b =>
                {
                    b.HasOne("RagChatbotSystem.DataAccess.Models.ChatMessage", "ChatMessage")
                        .WithMany()
                        .HasForeignKey("ChatMessageId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("RagChatbotSystem.DataAccess.Models.ChatSession", "ChatSession")
                        .WithMany()
                        .HasForeignKey("ChatSessionId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("RagChatbotSystem.DataAccess.Models.User", "CreatedByUser")
                        .WithMany()
                        .HasForeignKey("CreatedByUserId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("RagChatbotSystem.DataAccess.Models.Dataset", "Dataset")
                        .WithMany()
                        .HasForeignKey("DatasetId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("RagChatbotSystem.DataAccess.Models.CreditPackage", "RelatedPackage")
                        .WithMany("LedgerEntries")
                        .HasForeignKey("RelatedPackageId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("RagChatbotSystem.DataAccess.Models.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("ChatMessage");

                    b.Navigation("ChatSession");

                    b.Navigation("CreatedByUser");

                    b.Navigation("Dataset");

                    b.Navigation("RelatedPackage");

                    b.Navigation("User");
                });

            modelBuilder.Entity("RagChatbotSystem.DataAccess.Models.CreditPurchase", b =>
                {
                    b.HasOne("RagChatbotSystem.DataAccess.Models.User", "CreatedByUser")
                        .WithMany()
                        .HasForeignKey("CreatedByUserId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("RagChatbotSystem.DataAccess.Models.CreditPackage", "Package")
                        .WithMany("Purchases")
                        .HasForeignKey("PackageId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("RagChatbotSystem.DataAccess.Models.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("CreatedByUser");

                    b.Navigation("Package");

                    b.Navigation("User");
                });

            modelBuilder.Entity("RagChatbotSystem.DataAccess.Models.CreditWallet", b =>
                {
                    b.HasOne("RagChatbotSystem.DataAccess.Models.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("RagChatbotSystem.DataAccess.Models.Dataset", b =>
                {
                    b.HasOne("RagChatbotSystem.DataAccess.Models.User", "Creator")
                        .WithMany("Datasets")
                        .HasForeignKey("CreatedBy")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Creator");
                });

            modelBuilder.Entity("RagChatbotSystem.DataAccess.Models.DatasetPermission", b =>
                {
                    b.HasOne("RagChatbotSystem.DataAccess.Models.Dataset", "Dataset")
                        .WithMany("DatasetPermissions")
                        .HasForeignKey("DatasetId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("RagChatbotSystem.DataAccess.Models.User", "User")
                        .WithMany("DatasetPermissions")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Dataset");

                    b.Navigation("User");
                });

            modelBuilder.Entity("RagChatbotSystem.DataAccess.Models.Document", b =>
                {
                    b.HasOne("RagChatbotSystem.DataAccess.Models.Dataset", "Dataset")
                        .WithMany("Documents")
                        .HasForeignKey("DatasetId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("RagChatbotSystem.DataAccess.Models.User", "Uploader")
                        .WithMany("Documents")
                        .HasForeignKey("UploadedBy")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Dataset");

                    b.Navigation("Uploader");
                });

            modelBuilder.Entity("RagChatbotSystem.DataAccess.Models.ModelComparisonResult", b =>
                {
                    b.HasOne("RagChatbotSystem.DataAccess.Models.ModelComparisonRun", "Run")
                        .WithMany("Results")
                        .HasForeignKey("ModelComparisonRunId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Run");
                });

            modelBuilder.Entity("RagChatbotSystem.DataAccess.Models.ModelComparisonRun", b =>
                {
                    b.HasOne("RagChatbotSystem.DataAccess.Models.Dataset", "Dataset")
                        .WithMany()
                        .HasForeignKey("DatasetId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("RagChatbotSystem.DataAccess.Models.User", "RunByUser")
                        .WithMany()
                        .HasForeignKey("RunByUserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Dataset");

                    b.Navigation("RunByUser");
                });

            modelBuilder.Entity("RagChatbotSystem.DataAccess.Models.TeacherSubjectAssignment", b =>
                {
                    b.HasOne("RagChatbotSystem.DataAccess.Models.User", "AssignedByAdmin")
                        .WithMany()
                        .HasForeignKey("AssignedBy")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("RagChatbotSystem.DataAccess.Models.Dataset", "Dataset")
                        .WithOne("TeacherSubjectAssignment")
                        .HasForeignKey("RagChatbotSystem.DataAccess.Models.TeacherSubjectAssignment", "DatasetId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("RagChatbotSystem.DataAccess.Models.User", "Teacher")
                        .WithMany("TeacherSubjectAssignments")
                        .HasForeignKey("TeacherId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("AssignedByAdmin");

                    b.Navigation("Dataset");

                    b.Navigation("Teacher");
                });

            modelBuilder.Entity("RagChatbotSystem.DataAccess.Models.UserTokenUsage", b =>
                {
                    b.HasOne("RagChatbotSystem.DataAccess.Models.Dataset", "Dataset")
                        .WithMany()
                        .HasForeignKey("DatasetId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("RagChatbotSystem.DataAccess.Models.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Dataset");

                    b.Navigation("User");
                });

            modelBuilder.Entity("RagChatbotSystem.DataAccess.Models.VectorRecord", b =>
                {
                    b.HasOne("RagChatbotSystem.DataAccess.Models.Chunk", "Chunk")
                        .WithOne("VectorRecord")
                        .HasForeignKey("RagChatbotSystem.DataAccess.Models.VectorRecord", "ChunkId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("RagChatbotSystem.DataAccess.Models.Dataset", "Dataset")
                        .WithMany("VectorRecords")
                        .HasForeignKey("DatasetId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("RagChatbotSystem.DataAccess.Models.Document", "Document")
                        .WithMany("VectorRecords")
                        .HasForeignKey("DocumentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Chunk");

                    b.Navigation("Dataset");

                    b.Navigation("Document");
                });

            modelBuilder.Entity("RagChatbotSystem.DataAccess.Models.ChatMessage", b =>
                {
                    b.Navigation("Citations");
                });

            modelBuilder.Entity("RagChatbotSystem.DataAccess.Models.ChatSession", b =>
                {
                    b.Navigation("ChatMessages");
                });

            modelBuilder.Entity("RagChatbotSystem.DataAccess.Models.Chunk", b =>
                {
                    b.Navigation("Citations");

                    b.Navigation("VectorRecord");
                });

            modelBuilder.Entity("RagChatbotSystem.DataAccess.Models.CreditPackage", b =>
                {
                    b.Navigation("LedgerEntries");

                    b.Navigation("Purchases");
                });

            modelBuilder.Entity("RagChatbotSystem.DataAccess.Models.Dataset", b =>
                {
                    b.Navigation("ChatSessions");

                    b.Navigation("Chunks");

                    b.Navigation("DatasetPermissions");

                    b.Navigation("Documents");

                    b.Navigation("TeacherSubjectAssignment");

                    b.Navigation("VectorRecords");
                });

            modelBuilder.Entity("RagChatbotSystem.DataAccess.Models.Document", b =>
                {
                    b.Navigation("Chunks");

                    b.Navigation("Citations");

                    b.Navigation("VectorRecords");
                });

            modelBuilder.Entity("RagChatbotSystem.DataAccess.Models.ModelComparisonRun", b =>
                {
                    b.Navigation("Results");
                });

            modelBuilder.Entity("RagChatbotSystem.DataAccess.Models.User", b =>
                {
                    b.Navigation("ChatSessions");

                    b.Navigation("DatasetPermissions");

                    b.Navigation("Datasets");

                    b.Navigation("Documents");

                    b.Navigation("TeacherSubjectAssignments");
                });
#pragma warning restore 612, 618
        }
    }
}
